baseURL = "https://knid.me"

theme = 'hugo-bearblog'

title = "Knid's Website"
author = "Sinan Kanidagli"
copyright = "Copyright © 2025, Sinan Kanidagli"
languageCode = "en-US"

enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Physics student and backend developer with a passion for building systems that work — and understanding why they do. I work primarily with Go (Golang) and Python, developing robust APIs, backend services, and tools. My stack often includes PostgreSQL, Docker, and frameworks like Django/DRF. Previously, I’ve built mobile games with Unity, apps with Flutter/Dart, and various CLI and web applications. I’m also exploring embedded systems and low-level programming as hobbies. Outside of code, I’m always learning — especially in math, physics, and systems architecture. I occasionally dive into bug hunting, contribute to open source, and write about what I learn (or try to). 🛠 Check out my GitHub to see what I’m working on."

  # favicon = "images/favicon.png"
  # images = ["images/share.png"]
  profilePicture = "pp.jpg"
  title = "Knid's Website"
  hideMadeWithLine = true
  math = true

[markup]
  [markup.highlight]
    style = 'nord'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[menus]
[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 1
[[menus.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 2
[[menus.main]]
  name = 'Public Services'
  pageRef = '/public-services'
  weight = 3
[[menus.main]]
  name = 'Blog'
  pageRef = '/blog'
  weight = 4
[[menus.main]]
  name = 'PGP'
  pageRef = '/pgp'
  weight = 5
